class ListDummyMassageData {
  static final List<Map<String, dynamic>> messageData = [
    {
      "id": 1,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 2,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 3,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 4,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 5,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 6,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 7,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 8,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 9,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    {
      "id": 10,
      "name": "John Doe",
      "message": "Hello, how are you?",
      "specialty": "General Doctor",
      "time": "10:00 AM",
      "isRead": false,
    },
    
  ];
}
