name: doctors_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ^3.5.1

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # localization
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^8.1.6
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.5.7
  freezed_annotation:
    ^2.4.4
    # for dependency injection
  get_it: ^8.0.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.4
  pretty_dio_logger: ^1.4.0
  # localization
  intl: ^0.19.0
  # for splash screen
  flutter_native_splash: ^2.4.2
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.10+1
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3
  # firebase library
  firebase_core: ^3.8.1
  # reading and writing simple key-value pairs
  shared_preferences: ^2.3.4
  # Flutter library to load and cache network images.
  cached_network_image: ^3.4.1
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.2
  # easy way to add shimmer effect
  shimmer: ^3.0.0
  # show a convex tab in the bottom bar.
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
